language: python
python:
    - "3.6-dev"
install:
    - sudo apt-get update
    - pip install pipenv
    - pipenv install --dev
    - gem install mdl
script:
    - scripts/build_check.sh
    - pipenv run codecov
